version: "3.9"
services:
  postgres:
    image: postgres:16.4
    restart: on-failure
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: book-store
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
