// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID            int64       `json:"id"`
	Title         string      `json:"title"`
	Author        string      `json:"author"`
	Price         int64       `json:"price"`
	Description   string      `json:"description"`
	CoverImageUrl string      `json:"cover_image_url"`
	PublishedDate time.Time   `json:"published_date"`
	UserID        pgtype.Int8 `json:"user_id"`
	UpdatedAt     time.Time   `json:"updated_at"`
	CreatedAt     time.Time   `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
	UpdatedAt      time.Time `json:"updated_at"`
	CreatedAt      time.Time `json:"created_at"`
}
