// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBook(ctx context.Context, id int64) (Book, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
